################################################################################
# Automatically-generated file. Do not edit!
################################################################################

TODISASSEMBLE_SRCS_QUOTED := 
S_UPPER_SRCS_QUOTED := 
OBJ_SRCS_OS_FORMAT := 
TODISASSEMBLE_SRCS := 
O_SRCS_QUOTED := 
ASM_UPPER_SRCS := 
TODISASSEMBLE_SRCS_OS_FORMAT := 
O_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS_QUOTED := 
TOPREPROCESS_SRCS_OS_FORMAT := 
SX_SRCS_QUOTED := 
O_SRCS := 
TOPREPROCESS_SRCS_QUOTED := 
S_SRCS_OS_FORMAT := 
S_SRCS_QUOTED := 
C_SRCS_QUOTED := 
ASM_SRCS_OS_FORMAT := 
SX_SRCS := 
C_SRCS_OS_FORMAT := 
ASM_SRCS := 
S_UPPER_SRCS_OS_FORMAT := 
S_UPPER_SRCS := 
SX_SRCS_OS_FORMAT := 
ASM_SRCS_QUOTED := 
OBJ_SRCS_QUOTED := 
OBJ_SRCS := 
S_SRCS := 
TOPREPROCESS_SRCS := 
ASM_UPPER_SRCS_OS_FORMAT := 
C_SRCS := 
SX_DEPS_QUOTED := 
ASM_DEPS_QUOTED := 
S_DEPS_QUOTED := 
ASM_UPPER_DEPS_OS_FORMAT := 
S_UPPER_DEPS_OS_FORMAT := 
C_DEPS_QUOTED := 
ASM_DEPS_OS_FORMAT := 
S_DEPS := 
OBJS_QUOTED := 
C_DEPS := 
C_DEPS_OS_FORMAT := 
OBJS_OS_FORMAT := 
EXECUTABLES_OS_FORMAT := 
ASM_UPPER_DEPS := 
SX_DEPS := 
ASM_UPPER_DEPS_QUOTED := 
EXECUTABLES := 
OBJS := 
ASM_DEPS := 
SX_DEPS_OS_FORMAT := 
S_DEPS_OS_FORMAT := 
S_UPPER_DEPS := 
EXECUTABLES_QUOTED := 
S_UPPER_DEPS_QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Sources \
Project_Settings/Startup_Code \

